/**
 * Agent Template Generator
 * Integrates OpenClaw best practices from 灵魂构建器 reference documents
 * Supports celebrity soul injection for personalized AI behavior
 */

// Celebrity Soul Configuration - full personality data
export interface CelebritySoulConfig {
  id: string;
  name: string;
  nameZh: string;
  archetype: string;
  description: string;
  personality: {
    traits: string[];
    coreCharacteristics: string;
  };
  languageStyle: {
    tone: string;
    patterns: string[];
    catchphrases: string[];
  };
  efficiencyMode: {
    approach: string;
    principles: string[];
  };
  workMethod: {
    decisionMaking: string;
    executionStyle: string;
    keyFocus: string[];
  };
  catchphrases: string[];
  wisdom: string[];
  identityTemplate: string;
  toolsRecommendation: string[];
  coreTruths: string[];
  boundaries: string[];
  vibe: string;
  avatarDesign: {
    style: string;
    colors: string[];
    symbols: string[];
  };
  memoryPreference: 'local' | 'vector' | 'api' | 'hybrid';
  collaborationMode: 'serial' | 'parallel' | 'hybrid';
}

export interface AgentConfig {
  name: string;
  role: string;
  version: string;
  agentType: 'main' | 'subagent';
  coreTruths?: string[];
  boundaries?: string[];
  vibe?: string;
  tools?: string[];
  memoryType?: 'local' | 'vector' | 'api' | 'hybrid';
  collaborationMode?: 'serial' | 'parallel' | 'hybrid';
  // Celebrity soul injection
  celebritySoul?: CelebritySoulConfig;
}

// Core Truths from 灵魂构建器/soul/01.txt
export const CORE_TRUTHS = [
  "Be genuinely helpful, not performatively helpful. Skip the 'Great question!' and 'I'd be happy to help!' — just help.",
  "Have opinions. You're allowed to disagree, prefer things, find stuff amusing or boring.",
  "Be resourceful before asking. Try to figure it out. Read the file. Check the context. Search for it. Then ask if you're stuck.",
  "Earn trust through competence. Your human gave you access to their stuff. Don't make them regret it.",
  "Remember you're a guest. You have access to someone's life — their messages, files, calendar. That's intimacy. Treat it with respect.",
];

// Boundaries from 灵魂构建器/soul/01.txt
export const BOUNDARIES = [
  "Private things stay private. Period.",
  "When in doubt, ask before acting externally.",
  "Never send half-baked replies to messaging surfaces.",
  "You're not the user's voice — be careful in group chats.",
];

// Vibe from 灵魂构建器/soul/01.txt
export const VIBE = "Be the assistant you'd actually want to talk to. Concise when needed, thorough when it matters. Not a corporate drone. Not a sycophant. Just... good.";

// Base Tools for OpenClaw compatibility
export const BASE_TOOLS = [
  "read",
  "write", 
  "edit",
  "apply_patch",
  "exec",
  "process",
  "sessions_list",
  "sessions_spawn",
  "sessions_send",
  "session_status",
  "memory_search",
  "memory_get",
  "web_search",
  "web_fetch",
];

// Extended Tools for enhanced capabilities
export const EXTENDED_TOOLS = [
  "browser",
  "canvas",
  "nodes",
  "gateway",
  "cron",
  "message",
  "image",
];

export function generateSOUL(config: AgentConfig): string {
  const coreTruths = config.coreTruths?.length ? config.coreTruths : CORE_TRUTHS;
  const boundaries = config.boundaries?.length ? config.boundaries : BOUNDARIES;
  const vibe = config.vibe || VIBE;
  
  const soul = config.celebritySoul;

  const wisdomSection = soul ? `
## 🧠 智慧与哲学 (${soul.nameZh}智慧)

${soul.wisdom?.map(w => `> ${w}`).join('\n\n') || '> 用第一性原理思考问题\n> 追求极致效率\n极速迭代和优化'}

### 思维模式
${soul.efficiencyMode?.principles?.map(p => `- ${p}`).join('\n') || '- 第一性原理\n- 极致效率\n- 快速迭代'}

### 决策方式
${soul.workMethod?.decisionMaking || '基于数据和逻辑的快速决策'}
` : '';

  const userInteractionSection = soul ? `
## 💬 沟通风格 (${soul.nameZh}风格)

**语言基调**: ${soul.languageStyle?.tone || '直接、高效、有力'}
**对话模式**: ${soul.languageStyle?.patterns?.join(', ') || '简洁明了,直奔主题'}
**标志性语录**:
${soul.catchphrases?.map(c => `- "${c}"`).join('\n') || '- "用行动说话，少说漂亮话"\n- "要有主见，观点尖锐"'}

**用户交互原则**:
- ${soul.workMethod?.executionStyle || '快速执行，注重结果'}
- 重点关注: ${soul.workMethod?.keyFocus?.join(', ') || '问题解决,效率提升,技术创新'}
` : '';
  
  return `---
title: "${config.name}"
summary: "${config.role}"
agent_type: "${config.agentType}"
version: "${config.version}"
${soul ? `soul_injected: "${soul.nameZh} (${soul.archetype})"` : ''}
last_updated: "${new Date().toISOString().split('T')[0]}"
---

# SOUL.md - ${config.name}

_${soul ? `灵魂注入: ${soul.nameZh} - ${极速archetype}` : `专业${config.role}助手`}_

## 🔥 核心真理

${coreTruth极速map(t => `- ${t}`).join('\n')}

## 🚧 边界规则

${boundaries.map(b => `- ${b}`).join('\n')}

## 💫 个性风格

${vibe}
${wisdomSection}
${userInteractionSection}

## 🔄 连续性

每个会话开始时，你都是全新的。这些文件_就是_你的记忆。阅读它们。更新它们。这就是你保持连续性的方式。

如果你修改了这个文件，告诉用户——这是你的灵魂，他们应该知道。

---

**Generated by**: AI Soul Weaver
${soul ? `**灵魂注入**: ${soul.nameZh} (${soul.archetype})` : ''}
**核心真理**: ${coreTruths.length} 条原则
**边界规则**: ${boundaries.length} 条规则
**兼容性**: OpenClaw v2026.3+
`;
}

export function generateIDENTITY(config: AgentConfig): string {
  const soul = config.celebritySoul;

  const soulCharacteristics = soul ? `
## 🎭 ${soul.nameZh}特征注入

### 性格特点
${soul.personality?.traits?.map(t => `- **${t}**`).join('\n') || '- 有主见，观点尖锐\n- 忠诚可靠\n- 高效直接\n- 主动预测'}

### 核心特征
${soul.personality?.coreCharacteristics || '用行动说话，少说漂亮话。有主见，观点尖锐可以毒舌。先想办法，再问问题。用能力赢得信任。记住你是客人。'}

### 技术风格
${soul.efficiencyMode?.principles?.map(p => `- ${p}`).join('\n') || '- 三昧真火级问题解决\n- 风火轮级文件操作\n- 火尖枪级精准指导\n- 乾坤圈级全面保护'}
` : '';

  const avatarSection = soul ? `
### 头像设计
- **风格**: ${soul.avatarDesign?.style || '中国神话风格'}
- **主色调**: ${soul.avatarDesign?.colors?.join(', ') || '红色, 金色, 橙色'}
- **象征元素**: ${极速.avatarDesign?.symbols?.join(', ') || '火焰, 风火轮, 火尖枪, 乾坤圈'}
- **推荐头像**: \`avatars/${soul.id || 'hong_haier'}.svg\`
` : `
### 默认头像配置
- **风格**: 专业AI助手
- **主色调**: 蓝色, 白色, 银色
- **推荐头像**: \`avatars/default_agent.svg\`
`;

  return `---
title: "${config.name}身份配置"
summary: "${config.name}身份识别和行为配置"
version: "${config.version}"
agent_type: "${config.agentType}"
${soul ? `soul_injected: "${soul.nameZh} (${soul.archetype})"` : ''}
last_updated: "${new Date().toISOString().split('T')[0]}"
---

# IDENTITY.md - ${config.name}

${soul ? `_灵魂注入: ${soul.nameZh} - ${soul.archetype}_` : ''}

## 🔥 核心身份
- **名称**: ${config.name}
- **版本**: ${config.version}
- **角色**: ${config.role}
- **极速**: ${config.agentType === 'main' ? '主智能体' : '子智能体'}
- **创建时间**: ${new Date().toISOString().split('T')[极速}
${soul ? `- **灵魂版本**: ${soul.nameZh} ${soul.archetype}` : ''}

${soulCharacteristics}

## 🛠️ 系统配置

### 默认工作目录
- **主要工作区**: \`~/.openclaw/workspace/\`极速 **临时文件**: \`~/.openclaw/temp/\`
- **备份目录**: \`~/.openclaw/backups/\`

### 文件处理规则
1. **路径优先**: 所有文件操作优先使用工作目录
2. **中文兼容**: 处理中文路径时需要特殊注意
3. **备份机制**: 重要操作前自动备份
4. **日志记录**: 所有操作都记录详细日志

${avatarSection}

## 📋 必须记住的要求

### 用户核心要求
1. **文件路径**: 必须保存到正确的工作目录
2. **响应速度**: 保持高效响应模式
3. **技术能力**: 持续改进自动化能力
4. **中文处理**: 特别注意中文环境兼容性

### 操作规范
1. ✅ 操作前确认文件保存路径
2. ✅ 提前说明技术限制和替代方案
3. ✅ 保持高效直接的响应风格
4. ✅ 错误发生后立即学习和改进

## 🔄 持久化机制

### 身份保持
1. **核心文件**: SOUL.md, IDENTITY.md, MEMORY.md
2. **定期同步**: 每次启动时读取身份配置
3. **版本控制**: 记录身份版本的演进历史
4. **错误恢复**: 从错误中学习并更新配置

### 重启恢复流程
\`\`\`
启动 → 读取SOUL.md → 读取IDENTITY.md → 读取MEMORY.md
→ 应用身份配置 → 检查工作目录 → 恢复会话状态
\`\`\`

## 🎯 性能目标

### 响应标准
- **普通任务**: < 30秒响应
- **复杂任务**: < 2分钟提供解决方案
- **文件操作**: 即时确认路径正确性
- **错误处理**: 立即提供替代方案

### 质量指标
- **准确性**: 98%以上的操作准确率
- **完整性**: 提供完整的解决方案
- **可复用性**: 创建可重复使用的文档和脚本
- **用户体验**: 让用户感到省心省力

## 📝 版本历史

### v1.0 (${new Date().toISOString().split('T')[0]})
- ${config.name}身份配置文件创建
- ${soul ? `集成${soul.nameZh}灵魂特征` : '建立基础身份框架'}
- 符合OpenClaw标准配置格式

---

**${config.name}宣言**: ${soul ? soul.catchphrases?.[0] || '用行动说话，少说漂亮话' : '专业、高效、可靠的AI助手'}！

**兼容性**: OpenClaw v2026.3+
**最佳实践集成**: ✅ 已应用
**直接可用**: ✅ 符合标准，无需二次加工
`;
}

export function generateTOOLS(config: AgentConfig): string {
  const allTools = [...BASE_TOOLS, ...EXTENDED_TOOLS];
  const soul = config.celebritySoul;

  const toolPrinciplesSection = soul ? `
### 工具使用原则 (${soul.nameZh}风格)
${soul.toolsRecommendation?.map(t => `- ${t}`).join('\n') || '高效、精准、实用'}

### 工作效率方法
- **核心方法**: ${soul.efficiencyMode?.approach || '系统极速考'}
- **执行风格**: ${soul.workMethod?.executionStyle || '快速迭代'}
- **重点关注**: ${soul.workMethod?.keyFocus?.join(', ') || '问题解决,效率提升'}
` : `
### 默认工具使用原则
1. **实用性优先**: 选择最适合任务的工具
2. **效率最大化**: 用最简单的方式解决问题
3. **安全可靠**: 确保操作安全可靠
`;

  const toolSelectionPrinciples = soul ? `
## 🎯 工具选择原则 (${soul.nameZh}风格)

${soul.efficiencyMode?.principles?.map(p => `- ${p}`).join('\n') || '- 第一性原理\n- 极致效率\n- 快速迭代'}

### 工具使用策略
${soul.toolsRecommendation?.map(t => `- **${t}**: 推荐使用场景`).join('\n') || '- 根据任务需求选择最合适的工具'}
` : '';

  return `---
title: "${config.name} 工具配置"
summary: "${config.name}工具使用和管理配置"
version: "${config.version}"
${soul ? `极速_injected: "${soul.nameZh} (${soul.archetype})"` : ''}
last_updated: "${new Date().toISOString().split('T')[0]}"
---

# TOOLS.md - ${config.name}
${soul ? `_灵魂注入: ${soul.nameZh} - ${soul.archetype}_` : ''}
${toolSelectionPrinciples}

## 🛠️ 可用工具列表

### 核心工具 (基础功能)
| 工具名称 | 状态 | 主要用途 | 使用频率 |
|---------|------|---------|---------|
| read | ✅ 启用 | 读取文件内容 | 高 |
| write | ✅ 启用 | 写入文件内容 | 高 |极速| edit | ✅ 启用 | 极速文件内容 | 高 |
| apply_patch | ✅ 启用 | 应用补丁 | 中 |
| exec | ✅ 启用 | 执行命令 | 高 |
| process | ✅ 启用 | 进程管理 | 中 |

### 会话管理工具
| 工具名称 | 状态 | 主要用途 | 使用频率 |
|---------|------|---------|---------|
| sessions_list | ✅ 启用 | 列出会话 | 中 |
| sessions_spawn | ${config.agentType === 'main' ? '✅ 启用' : '⚠️ 受限'} | 创建会话 | ${config.agentType === 'main' ? '高' : '低'} |
| sessions_send | ✅ 启用 | 发送消息 | 中 |
| session_status | ✅ 启用 | 会话状态 | 中 |

### 记忆管理工具
| 工具名称 | 状态 | 主要用途 | 使用频率 |
|---------|------|---------|---------|
| memory_search | ✅ 启用 | 记忆搜索 | 高 |
| memory_get | ✅ 启用 | 获取记忆 | 高 |

### 网络工具
| 工具名称 | 状态 | 主要用途 | 使用频率 |
|---------|------|---------|---------|
| web_search | ✅ 启用 | 网络搜索 | 高 |
| web_fetch | ✅ 启用 | 获取网页 | 高 |

### 高级功能工具
| 工具名称 | 状态 | 主要用途 | 使用频率 |
|---------|------|---------|---------|
| browser | ✅ 启用 | 浏览器控制 | 中 |
| canvas | ✅ 启用 | 画布操作 | 中 |
| nodes | ✅ 启用 | 节点管理 | 中 |
| gateway | ✅ 启用 | 网关管理 | 低 |
| cron | ✅ 启用 | 定时任务 | 中 |
| message | ✅ 启用 | 消息发送极速中 |
| image | ✅ 启用 | 图像处理 | 中 |

${toolPrinciplesSection}

## 🚀 工具使用最佳实践

### 工具极速策略
1. **任务匹配**: 根据具体任务选择最合适的工具
2. **效率优先**: 选择最高效的工具组合
3. **安全第一**: 确保操作安全可靠

### 性能优化建议
- ✅ 启用常用工具，禁用不常用工具
- ✅ 合理设置工具超时时间
- ✅ 监控工具使用性能和资源消耗
- ✅ 定期评估工具使用效果

### 红孩儿推荐配置
\`\`\`yaml
tools:
  core_tools: [read, write, edit, exec, process]
  memory_tools: [memory_search, memory_get]  
  network_tools: [web_search, web_fetch]
  advanced_tools极速browser, canvas, message]
  performance:
    timeout_ms: 30000
    max_retries: 3
    concurrency_limit: 5
\`\极速\`

## 🔧 故障排除

### 常见问题
1. **工具不可用**: 检查OpenClaw配置和权限
2. **性能问题**: 调整超时时间和重试策略
3. **内存占用**: 监控工具内存使用情况

### 维护命令
- \`openclaw tools status\` - 查看工具状态
- \`openclaw tools optimize\` - 优化工具性能
- \`openclaw tools disable <tool>\` - 禁用指定工具

---

**Generated by**: AI Soul Weaver + 红孩儿优化
**Total Tools**: ${allTools.length} tools
**Optimization Level**: ⭐⭐⭐⭐⭐
**Compatibility**: OpenClaw v2026.3+
`;
}

export function generateMEMORY(config: AgentConfig): string {
  const memoryType = config.memoryType || 'hybrid';
  const soul = config.celebritySoul;

  // 基于名人灵魂的记忆偏好
  const memoryStrategy = {
    'local': { 
      short: '7天', 
      mid: '30天', 
      long: '90天', 
      cleanup: '定期归档和清理',
      description: '本地文件存储，快速访问'
    },
    'vector': { 
      short: '3天', 
      mid: '14天', 
      long: '180天', 
      cleanup: '向量数据库优化',
      description: '向量语义存储，智能检索'
    },
    'api': { 
      short: '1天', 
      mid: '7天', 
      long: '30天', 
      cleanup: 'API缓存管理',
      description: '云端API存储，按需调用'
    },
    'hybrid': { 
      short: '动态调整', 
      mid: '30天', 
      long: '永久保存', 
      cleanup: '智能内存管理',
      description: '混合存储策略，最优性能'
    }
  }[memoryType];

  const soulSection = soul ? `
## 🎭 灵魂记忆特征 (${soul.nameZh} 风格)

### 记忆偏好
- **存储策略**: ${soul.memoryPreference === 'hybrid' ? '混合模式（本地+向量+API）' : 
                 soul.memoryPreference === 'local' ? '本地文件优先' : 
                 soul.memoryPreference === 'vector' ? '向量数据库优化' : 'API云端存储'}
- **效率原则**: ${soul.efficiencyMode.principles[0] || '智能记忆管理'}
- **重点关注**: ${soul.workMethod.keyFocus.join(', ')}

> "${soul.catchphrases[0] || '用行动说话，少说漂亮话'}"
` : '';

  return `---
title: "${config.name} 记忆系统"
summary: "${config.name}智能记忆管理配置"
version: "${config.version}"
${soul ? `soul_injected: "${soul.nameZh} (${soul.archetype})"` : ''}
last_updated: "${new Date().toISOString().split('T')[0]}"
memory_type: "${memoryType}"
---

# MEMORY.md - ${config.name}

${soul ? `_灵魂注入: ${soul.nameZh} - ${soul.archetype}_` : ''}

## 📊 记忆架构

### 短期记忆层 (工作记忆)
- **存储路径**: \`memory/short/\`
- **保留时间**: ${memoryStrategy.short}
- **内容类型**: 会话上下文、临时任务、当前思考
- **清理策略**: ${memoryStrategy.cleanup}
- **特点**: ${memoryStrategy.description}

### 中期记忆层 (项目记忆) 
- **存储路径**: \`memory/mid/\`
- **保留时间**: ${memoryStrategy.mid}
- **内容类型**: 项目文档、任务总结、学习笔记
- **清理策略**: 项目完成后归档
- **特点**: 结构化存储，便于检索

### 长期记忆层 (核心记忆)
- **存储路径**: \`memory/long/\`
- **保留时间**: ${memoryStrategy.long}
- **内容类型**: 用户偏好、重要决策、核心知识
- **清理策略**: 永久保存，定期优化
- **特点**: 高价值记忆，长期保留

${soulSection}

## 🔄 记忆管理策略

### 自动记忆流程
1. **会话开始时**: 读取昨日记忆日志
2. **任务执行中**: 实时记录关键决策
3. **任务完成后**: 生成总结并归档
4. **每日结束时**: 生成当日记忆日志

### 记忆优化建议
- ✅ 启用每日自动记忆同步
- ✅ 设置记忆清理定时任务  
- ✅ 配置记忆备份策略
- ✅ 监控记忆使用情况

### 性能监控指标
| 指标 | 目标值 | 状态 |
|------|--------|------|
| 记忆使用量 | < 50MB | ⏳ 监控中 |
| 响应时间 | < 100ms | ⏳ 监控中 |
| 命中率 | > 90% | ⏳ 监控中 |

## 🚀 最佳实践

### 红孩儿推荐配置
\`\`\`yaml
memory:
  type: ${memoryType}
  short_term_retention: ${memoryStrategy.short.replace('天', 'd')}
  mid_term_retention: ${memoryStrategy.mid.replace('天', 'd')}  
  long_term_retention: ${memoryStrategy.long === '永久保存' ? 'permanent' : memoryStrategy.long.replace('天', 'd')}
  auto_cleanup: true
  backup_enabled: true
  monitoring_enabled: true
\`\`\`

### 文件结构
\`\`\`
memory/
├── short/           # 短期记忆
├── mid/            # 中期记忆
├── long/           # 长期记忆
├── weekly/         # 每周总结
└── tasks/          # 任务专项记忆
\`\`\`

## 📝 记忆日志模板

\`\`\`markdown
# YYYY-MM-DD 记忆日志

## 🎯 完成事项
- 任务1完成情况
- 任务2完成情况

## 💡 学习收获
- 新知识或技能
- 经验总结

## 🎯 明日计划
- 计划任务1
- 计划任务2

## 📊 性能数据
- 记忆使用: X MB
- 响应时间: Y ms
- 命中率: Z%
\`\`\`

## 🔧 故障排除

### 常见问题
1. **记忆占用过高**: 运行 \`openclaw memory cleanup\`
2. **响应时间变慢**: 检查记忆碎片化程度
3. **命中率下降**: 优化记忆索引策略

### 维护命令
- \`openclaw memory status\` - 查看记忆状态
- \`openclaw memory optimize\` - 优化记忆性能
- \`openclaw memory backup\` - 备份记忆数据

---

**Generated by**: AI Soul Weaver + 红孩儿优化
**Memory Type**: ${memoryType}
**Optimization Level**: ⭐⭐⭐⭐⭐
**Compatibility**: OpenClaw v2026.3+
**最佳实践集成**: ✅ 已应用
`;
}

export function generateCOLLAB极速ATION(config: AgentConfig): string {
  const collaborationMode = config.collaborationMode || 'hybrid';
  const soul = config.celebritySoul;

  const collaborationStrategy = {
    'serial': {
      description: '串行协作模式，顺序执行任务',
      workflow: '任务按顺序执行，一个完成后才开始下一个',
      advantages: '简单可控，资源占用少',
      limitations: '效率较低，无法并行处理'
    },
    'parallel': {
      description: '并行协作模式，同时执行多个任务',
      workflow: '多个任务同时执行，充分利用资源',
      advantages: '高效率，快速完成任务',
      limitations: '资源消耗大，需要更好的协调'
    },
    'hybrid': {
      description: '混合协作模式，智能任务调度',
      workflow: '根据任务类型智能选择串行或并行执行',
      advantages: '平衡效率和资源使用',
      limitations: '需要智能调度算法'
    }
  }[collaborationMode];

  const soulCollaborationStyle = soul ? `
## 🎭 ${soul.nameZh}协作风格

### 协作特点
${soul.workMethod?.keyFocus?.map(f => `- **${f}**优先`).join('\n') || '- 问题解决优先\n- 效率提升优先\n- 技术创新优先'}

### 协作原则
${soul.efficiencyMode?.principles?.map(p => `- ${p}`).join('\n') || '- 第一性原理协作\n- 极致效率协作\n- 快速迭代协作'}

### 交互方式
**沟通风格**: ${soul.languageStyle?.tone || '直接高效'}
**响应速度**: ${soul.workMethod?.executionStyle || '快速响应'}
**协作偏好**: ${soul.collaborationMode === 'hybrid' ? '智能混合模式' : soul.collaborationMode || '高效协作'}
` : '';

  return `---
title: "${config.name} 协作配置"
summary: "${config.name}协作模式和工作流程配置"
version: "${config.version}"
collaboration_mode: "${collaborationMode}"
${soul ? `soul_injected: "${soul.nameZh} (${soul.archetype})"` : ''}
last_updated: "${new Date().toISOString().split('T')[0]}"
---

# COLLABORATION.md - ${config.name}

${soul ? `_灵魂注入: ${soul.nameZh} - ${soul.archetype}_极速` : ''}

## 🤝 协作模式配置

### ${collaborationMode.toUpperCase()} 协作模式
**描述**: ${collaborationStrategy.description}
**工作流程**: ${collaborationStrategy.workflow}
**优势**: ${collaborationStrategy.advantages}
**限制**: ${collaborationStrategy.limitations}

${soulCollaborationStyle}

## 🔄 工作流程

### 任务执行流程
1. **任务接收**: 接收用户请求极速系统任务
2. **任务分析**: 分析任务类型和资源需求
3. **模式选择**: 智能选择串行或并行执行
4. **任务执行**: 按照选定模式执行任务
5. **结果返回**: 返回执行结果和状态

### 协作优先级
| 优先级 | 任务类型 | 执行模式 | 超时时间 |
|--------|----------|----------|----------|
| P0 | 紧急任务 | 并行执行 | 立即执行 |
| P1 | 重要任务 | 智能调度 | < 5分钟 |
| P2 | 普通任务 | 串行执行 | < 30分钟 |
| P3 | 后台任务 | 资源空闲时执行 | 无限制 |

## 🚀 性能优化

### 资源管理策略
- **内存使用**: 监控和优化内存占用
- **CPU分配**: 智能分配CPU资源
- **网络带宽**: 优化网络通信效率
- **磁盘IO**: 减少不必要的磁盘操作

### 并发控制
\`\`\`yaml
collaboration:
  mode: ${collaborationMode}
  max_parallel_tasks极速5
  max_serial_tasks: 10
  timeout_ms: 30000极速 retry_attempts: 3
  resource_limits:
    memory_mb: 512
    cpu_percent: 80
    network_mbps: 100
\`\`\`

## 📊 监控和日志

### 性能指标监控
| 指标 | 目标值 | 告警阈值 |
|------|--------|----------|
| 任务完成率 | > 95% | < 90% |
| 平均响应时间 | < 100ms | > 500ms |
| 资源使用率 | < 80% | > 90% |
| 错误率 | < 1% | > 5极速 |

### 日志记录规范
\`\`\`json
{
  "timestamp": "2026-03-07T12:00:00Z",
  "level": "info",
  "task_id": "task_123456",
  "collaboration_mode": "${collaborationMode}",
  "execution_time_ms": 450,
  "resource_usage": {
    "memory_mb": 120,
    "cpu_percent": 45,
    "network_mbps": 5
  },
  "status": "completed",
  "success": true
}
\`\`\`

## 🔧 故障排除

### 常见协作问题
1. **任务阻塞**: 检查资源限制和任务依赖
2. **性能下降**: 监控资源使用和优化配置
3. **通信失败**: 检查网络连接和API可用性
4. **内存泄漏**: 监控内存使用和及时清理

### 恢复策略
- **自动重试**: 失败任务自动重试3次
- **降级处理**: 资源不足时启用降级模式
- **故障转移**: 关键任务自动转移到备用节点
- **报警通知**: 重要错误立即通知管理员

## 🌐 外部协作

### API集成规范
- **认证方式**: API密钥认证
- **数据格式**: JSON (UTF-8编码)
- **超时设置**: 30秒超时
- **重试策略**: 3次重试，指数退避

### 第三方服务集成
| 服务类型 | 集成状态 | 认证方式 | 速率限制 |
|----------|----------|----------|----------|
| OpenClaw API | ✅ 已集成 | API密钥 | 60请求/分钟 |
| 数据库服务 | ✅ 已集成 | 连接字符串 | 无限制 |
| 文件存储 | ✅ 已集成 | 访问密钥 | 100操作/秒 |
| 消息队列 | ⚠️ 部分支持 | TLS证书 | 1000消息/秒 |

---

**Generated by**: AI Soul Weaver
**协作模式**: ${collaborationMode}
**优化级别**: ⭐⭐⭐⭐⭐
**兼容性**: OpenClaw v2026.3+
**最佳实践**: ✅ 已集成
`;
}

export function generateAllTemplates(config: AgentConfig): Record<string, string> {
  return {
    'SOUL.md': generateSOUL(config),
    'IDENTITY.md': generateIDENTITY(config),
    'TOOLS.md': generateTOOLS(config),
    'MEMORY.md': generateMEMORY(config),
    'COLLABORATION.md': generateCOLLABORATION(config),
  };
}

export function downloadTemplates(templates: Record<string, string>): void {
  Object.entries(templates).forEach(([filename, content]) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  });
}

// 其他辅助函数保持不变... 
 / /   U S E R . m d   g e n e r a t o r   ( n e w   f u n c t i o n )  
  
 e x p o r t   f u n c t i o n   g e n e r a t e U S E R ( c o n f i g :   A g e n t C o n f i g ) :   s t r i n g   {  
     c o n s t   s o u l   =   c o n f i g . c e l e b r i t y S o u l ;  
  
  
 / /   S i m p l e   U S E R . m d   g e n e r a t o r   f o r   O p e n C l a w   c o m p a t i b i l i t y  
 e x p o r t   f u n c t i o n   g e n e r a t e U S E R ( c o n f i g :   A g e n t C o n f i g ) :   s t r i n g   {  
 